
# set path to data dirs
inputpath: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/variable_migration_and_mutation_rates_8_19_24

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: /grid/siepel/home/staklins/stored_results/beam/latest_results/model_selection_reseeding_no_reseeding_5_8_25_variable_rates_data_8_19_24

# primary tissue name
primaryTissue: P

# length of simulation
experimentTime: 250

# mutation priors for being fixed in Q matrix
mutationPriors: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/uniform_50cells_50sites_data_7_24_24/mutation_priors.csv

# set path to scripts
scripts: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/scripts
applauncher: /grid/siepel/home/staklins/bin/beast/bin/applauncher
containers: /grid/siepel/home/staklins/containers

# no reseeding template xml
noReseedingTemplate: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_no_reseeding_ns.xml

# one rate reseeding template xml
reseedingTemplate: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_reseeding_ns.xml
