
# set path to data dirs
inputpath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/quinn_2021_real_data/GSE161363"

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/quinn_2021_lung_cancer_data_1_22_25"

# set the number of threads (make sure it matched the cluster.yaml specifications for the rules using threads as command line input)
threads: 5

# maximum jaccard distance between two cells from the same tissue to be considered the same cell in the downsampling procedure
downsample_threshold: 0

# primary tissue name
primaryTissue: LL

# set path to scripts
scripts: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/scripts

# set necessary paths to beast dependencies
treeannotator: /grid/siepel/home_norepl/staklins/bin/beast/bin/treeannotator
logcombiner: /grid/siepel/home_norepl/staklins/bin/beast/bin/logcombiner

# set path to beam custom BEAST2 package runnable jar file
beamJar: /grid/siepel/home_norepl/staklins/beam/beam.jar

# set path to the beam model xml template file
gtrXml: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/inputs/beam_gtr_mcmc_template.xml
randomXml: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/inputs/beam_random_mcmc_template.xml

# set the length of the experiment
# for Quinn et al. 2021 data, the experiment lengths vary by mouse and are found in the supplementary figures caption by searching "days post-implantation"
experimentTime:
  5k: 54
  10k: 53
  100k: 67
  30k: 80

# set the desired mcmc chain length
mcmcLength: 50000000

# set the desired number of parallel mcmc chains to run
numChains: 3

# set the minimum ess to include a chain in the combined output across chains (default: 200)
essCutoff: 200
