__default__:
  cores: 5
  mem: '2G'
  logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
  logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'
  runtime: 168:00:00  # timelimit for each job in hours:minutes:seconds

runLAML:
  cores: 25

  