
# set path to data dirs
fastqPath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/ryan_prostate_cancer_data_cancer_discovery_7_3_24/fastq_files"
# fastqPath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/billy_bladder_cancer_data_7_1_24/fastq_raw"

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/serio_prostate_cancer_data_11_11_24"
# outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/billy_bladder_cancer_data_11_11_24"

# whether to model dropouts or just consider them as unedited sites
modelDropouts: true

# threshold for downsampling
downsampleTipNumThreshold: 150 # any CP with more ASVs than this will be downsampled
downsampleDistanceThreshold: 0.3 # for CPs being downsampled, this threshold will be used. 0.0 will always bypass downsampling

# primary tissue name
primaryTissue: 
  MMUS1457: PRL
  MMUS1466: PRL
  MMUS1467: PRL
  MMUS1469: PRL
  MMUS1492: PRL
  MMUS1495: PRL
  MMUS1544: PRL
  MMUS1588: PRL
  MMUS1874: PRL
  MMUS1875: PRL

# primaryTissue: 
#   MMUS1834: BDR
#   MMUS3012: BDR
#   MMUS3011: BDR
#   MMUS3010: BDR
#   MMUS1910: BDR2  # specific to Billy's data, where MMUS1910 has two primary tumor labels
#   MMUS1957: BDR
#   MMUS1782: BDR

# set path to scripts
scripts: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/scripts

# set necessary paths to beast dependencies
treeannotator: /grid/siepel/home_norepl/staklins/bin/beast/bin/treeannotator
logcombiner: /grid/siepel/home_norepl/staklins/bin/beast/bin/logcombiner

# set path to metastabayes custom BEAST2 package runnable jar file
metastabayesJar: /grid/siepel/home_norepl/staklins/metastabayes/metastabayes.jar

# set path to the metastabayes model xml template file
xml: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/inputs/metastabayes_mcmc_template.xml

# set the length of the experiment

# for Ryan's published cancer discovery prostate cancer data
experimentTime: 
  MMUS1457: 344
  MMUS1466: 400
  MMUS1467: 420
  MMUS1469: 421
  MMUS1492: 393
  MMUS1495: 364
  MMUS1544: 224
  MMUS1588: 421
  MMUS1874: 421
  MMUS1875: 398

# # for Billy's bladder cancer data
# experimentTime: 
#   MMUS1834: 420
#   MMUS3012: 315
#   MMUS3011: 425
#   MMUS3010: 423
#   MMUS1910: 422
#   MMUS1957: 420
#   MMUS1782: 218

# set the desired maximum mcmc chain length
mcmcLength: 50000000

# set the desired number of parallel mcmc chains to run
numChains: 3

# set the minimum ess to include a chain in the combined output across chains (default: 200)
essCutoff: 200
