__default__:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}.err'
  runtime: 24:00:00

runLAML:
  cores: '{params.threads}'
  mem: '1G'

runBeam:
  cores: '{params.threads}'
  mem: '2G'


  