
# set path to data dirs
inputpath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/variable_migration_and_mutation_rates_8_19_24"

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/information_content_GTI_model_12_13_24_variable_rates_data_8_19_24"

# primary tissue name
primaryTissue: P

# length of simulation/experiment
generations: 250

# set path to scripts
scripts: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/scripts
beamJar: /grid/siepel/home_norepl/staklins/beam/beam.jar

# template xml with model selection mcmc specs
xmlTemplate: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/inputs/beam_ns_template_gti.xml


# number of nested sampling replicates to run for each model
numReps: 1

# number of particles per rep to use for nested sampling per run
numParticles: 1 # Keep this fixed to 1 since we use numReps above to parallelize more than one particle instead of using more particles per run
