
# set path to data dirs
fastqPath: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/ryan_prostate_cancer_data_cancer_discovery_7_3_24/fastq_files

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: /grid/siepel/home/staklins/stored_results/beam/latest_results/serio_prostate_cancer_data

# set the asv count threshold for filtering in evotracer
asvThreshold: 3

# thresholds for consensus classifications and times
thresholds: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]

# threshold for downsampling
downsampleTipNumThreshold: 10000000 # any CP with more ASVs than this will be downsampled
downsampleDistanceThreshold: 0.0 # for CPs being downsampled, this threshold will be used. 0.0 will always bypass downsampling

# primary tissue name
primaryTissue: 
  MMUS1457: PRL
  MMUS1466: PRL
  MMUS1467: PRL
  MMUS1469: PRL
  MMUS1492: PRL
  MMUS1495: PRL
  MMUS1544: PRL
  MMUS1588: PRL
  MMUS1874: PRL
  MMUS1875: PRL

# set path to scripts and executables
scripts: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/scripts
containers: /grid/siepel/home/staklins/containers
treeannotator: /grid/siepel/home/staklins/bin/beast/bin/treeannotator
logcombiner: /grid/siepel/home/staklins/bin/beast/bin/logcombiner

# set path to the beam model xml template file
gtrXml: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_gtr_mcmc_template.xml
randomXml: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_random_mcmc_template.xml

noReseedingNS: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_no_reseeding_ns.xml
reseedingNS: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_reseeding_ns.xml

# Length of experiment for Ryan's published cancer discovery prostate cancer data
experimentTime: 
  MMUS1457: 344
  MMUS1466: 400
  MMUS1467: 420
  MMUS1469: 421
  MMUS1492: 393
  MMUS1495: 364
  MMUS1544: 224
  MMUS1588: 421
  MMUS1874: 421
  MMUS1875: 398

# set the desired maximum mcmc chain length
mcmcLength: 1000000000

# set the desired number of parallel mcmc chains to run
numChains: 3

# set the minimum ess to include a chain in the combined output across chains
essCutoff: 200