__default__:
  cores: '{params.threads}'
  mem: '{params.mem}'
  logout: '{wildcards.outdir}/job_logs/{wildcards.sample}/{wildcards.cp}/{rule}.out'
  logerror: '{wildcards.outdir}/job_logs/{wildcards.sample}/{wildcards.cp}/{rule}.err'
  runtime: '24:00:00'

runEvotracer:
  logout: '{wildcards.outdir}/job_logs/{wildcards.sample}/{rule}.out'
  logerror: '{wildcards.outdir}/job_logs/{wildcards.sample}/{rule}.err'
