
# input fastq files
fastqPath: "/grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/data/lise_in_vitro_migration_graph_4_23_25/fastq_renamed"

# output directory
outdir: "/grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/results/in_vitro_data_4_24_25"

# set the asv count threshold for filtering in evotracer
asvThreshold: 3

# set the path to the scripts
scripts: /grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/scripts

# set the path to the gtr xml template file
gtrXml: /grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/inputs/beam_gtr_mcmc_template.xml

# Length of experiment
experimentTime: 24

# set the desired maximum mcmc chain length
mcmcLength: 250000000

# set the desired number of parallel mcmc chains to run
numChains: 3

# primary tissue
primaryTissue: "P"

# ground truth graphs
scenario:
  1: "/grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/results/in_vitro_data_4_24_25/scenario1_ground_truth.csv"
  2: "/grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/results/in_vitro_data_4_24_25/scenario2_ground_truth.csv"
  3: "/grid/siepel/home/staklins/bayesian_phylogenetic_metastasis/results/in_vitro_data_4_24_25/scenario3_ground_truth.csv"

# dependencies
logcombiner: /grid/siepel/home/staklins/bin/beast/bin/logcombiner