__default__:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}.err'
  runtime: 24:00:00  # 12 hours timelimit for all methods

runMachina:
  cores: '{params.threads}'
  mem: '5G'

runMach2:
  cores: '{params.threads}'
  mem: '5G'

runBeam:
  cores: '{params.threads}'
  mem: '2G'

plotPrecisionRecall:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{rule}.out'
  logerror: '{outdir}/job_logs/{rule}.err'

runMetient:
  cores: '{params.threads}'
  mem: '5G'

runLAML:
  cores: '{params.threads}'
  mem: '5G'

runBeamGtrNs:
  cores: '{params.threads}'
  mem: '2G'

runBeamRandomNs:
  cores: '{params.threads}'
  mem: '2G'

  