__default__:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}.err'
  runtime: 24:00:00  # 12 hours timelimit for all methods

runMachina:
  cores: '{params.threads}'
  mem: '5G'

runMetastabayes:
  cores: '{params.threads}'
  mem: '2G' # need total of 5GB for java BEAST2 submission command in the Snakefile

plotPrecisionRecall:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{rule}.out'
  logerror: '{outdir}/job_logs/{rule}.err'

runMetient:
  cores: 25
  mem: '1G'

  