inputpath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/uniformMigration_only_pR_50sites_6_24_24/pR"
outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/test"

