
# set path to data dirs
inputpath: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/data/uniformMigration_only_pR_50sites_6_24_24/pR"

# set where output should go (data is also copied there initially to retain original data in raw form)
outdir: "/grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/results/test"

# primary tissue name
primaryTissue: P

# set path to scripts
scripts: /grid/siepel/home_norepl/staklins/bayesian_phylogenetic_metastasis/scripts

# set necessary paths to beast dependencies
treeannotator: /grid/siepel/home_norepl/staklins/bin/beast/bin/treeannotator
logcombiner: /grid/siepel/home_norepl/staklins/bin/beast/bin/logcombiner

# set path to metastabayes custom BEAST2 package runnable jar file
metastabayes: /grid/siepel/home_norepl/staklins/metastabayes/metastabayes.jar

# set the length of the simulation datasets in number of cell divisions
generations: 250

# set the matrix structure and number of rates for the tissue rate matrix in the metastabayes model
# currently set to GTI model with 10 tissues
matrixStructure: "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99"
numRates: 100

# set the desired mcmc chain lenght
mcmclength: 10000
