__default__:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}.err'
  runtime: 120:00:00  # timelimit for all methods in hr:min:sec

downsampleInputsJaccard:
  cores: '{params.threads}'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}_{wildcards.threshold}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}_{wildcards.threshold}.err'
  mem: '1G'

downsampleInputsTree:
  cores: '{params.threads}'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}_{wildcards.threshold}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}_{wildcards.threshold}.err'
  mem: '1G'

runBeam:
  cores: 5
  mem: '2G' # need total of 5GB for java BEAST2 submission command in the Snakefile

plotPrecisionRecall:
  cores: 1
  mem: '5G'
  logout: '{outdir}/job_logs/{rule}.out'
  logerror: '{outdir}/job_logs/{rule}.err'

  