__default__:
  cores: '{params.threads}'
  mem: '{params.mem}'
  logout: '{outdir}/job_logs/{wildcards.sim}/{rule}.out'
  logerror: '{outdir}/job_logs/{wildcards.sim}/{rule}.err'
  runtime: 240:00:00

plotPrecisionRecall:
  logout: '{outdir}/job_logs/{rule}.out'
  logerror: '{outdir}/job_logs/{rule}.err'

collectMutualInformationAndPlot:
  logout: '{outdir}/job_logs/{rule}.out'
  logerror: '{outdir}/job_logs/{rule}.err'
  