
# set path to data dirs
# inputpath: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/uniform_50cells_50sites_data_7_24_24
inputpath: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/variable_migration_and_mutation_rates_8_19_24

# set where output should go
# outdir: /grid/siepel/home/staklins/stored_results/beam/latest_results/snakemake_performance_uniform_50cells_50sites_data_7_24_24
outdir: /grid/siepel/home/staklins/stored_results/beam/latest_results/variable_migration_and_mutation_rates_data_8_19_24

# mutation priors for being fixed in Q matrix
mutationPriors: /grid/siepel/home/staklins/stored_data/crispr_barcode_related_data/uniform_50cells_50sites_data_7_24_24/mutation_priors.csv

# set path to the beam model xml template files
gtrXml: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_gtr_mcmc_template.xml
randomXml: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/inputs/beam_random_mcmc_template.xml

# primary tissue name
primaryTissue: P

# set the length of the simulation datasets in number of cell divisions
generations: 250

# set the desired mcmc chain length and number of chains to run in parallel
mcmcLength: 5000000
numChains: 3

# set the minimum ess to include a chain in the combined output across chains (default: 200)
essCutoff: 200

# probability threshold for the consensus tree from the beast posterior probability tree
consensusThreshold: 0.5

# set path to scripts and executables
scripts: /grid/siepel/home/staklins/projects/crispr_barcode/bayesian_phylogenetic_metastasis/scripts
containers: /grid/siepel/home/staklins/containers
treeannotator: /grid/siepel/home/staklins/bin/beast/bin/treeannotator
logcombiner: /grid/siepel/home/staklins/bin/beast/bin/logcombiner
